// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFzAJPSqI6HjVpaEFv3Db3cDsILvk4zyU',
    appId: '1:195995846502:web:9f87a9fa177d8df9f76aa7',
    messagingSenderId: '195995846502',
    projectId: 'studia-6cacf',
    authDomain: 'studia-6cacf.firebaseapp.com',
    storageBucket: 'studia-6cacf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_eePlHHBguFRQtc56VmWfKFLGTiyfoik',
    appId: '1:195995846502:android:be31dc944e47b3c5f76aa7',
    messagingSenderId: '195995846502',
    projectId: 'studia-6cacf',
    storageBucket: 'studia-6cacf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsnQnqnVtJFggcYqEs0M6ZrunkyCHSAUY',
    appId: '1:195995846502:ios:f3baaa1dac7c7889f76aa7',
    messagingSenderId: '195995846502',
    projectId: 'studia-6cacf',
    storageBucket: 'studia-6cacf.appspot.com',
    iosClientId: '195995846502-nsacag3ba3gvb02q7o8nnp8gjqdi2gst.apps.googleusercontent.com',
    iosBundleId: 'com.example.studia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsnQnqnVtJFggcYqEs0M6ZrunkyCHSAUY',
    appId: '1:195995846502:ios:f3baaa1dac7c7889f76aa7',
    messagingSenderId: '195995846502',
    projectId: 'studia-6cacf',
    storageBucket: 'studia-6cacf.appspot.com',
    iosClientId: '195995846502-nsacag3ba3gvb02q7o8nnp8gjqdi2gst.apps.googleusercontent.com',
    iosBundleId: 'com.example.studia',
  );
}
